SELECT ROUND(AVG(NU_NOTA_CN)) AS M_CN
     , ROUND(AVG(NU_NOTA_CH)) AS M_CH
     , ROUND(AVG(NU_NOTA_LC)) AS M_LC
     , ROUND(AVG(NU_NOTA_MT)) AS M_MT
     , ROUND(AVG(NU_NOTA_REDACAO)) AS M_RE
     , SG_UF_PROVA AS UF_PROVA
  FROM MICRODADOS_ENEM
 WHERE IN_TREINEIRO = 0
   AND TP_PRESENCA_CN = 1
   AND TP_PRESENCA_LC = 1
   AND TP_PRESENCA_MT = 1
   AND TP_STATUS_REDACAO = 1
 GROUP BY UF_PROVA
 ORDER BY UF_PROVA;