SELECT CO_HABILIDADE,
       SG_UF_PROVA,
       ROUND(SUM(ACERTO) / (MAX(TOTAL_PESSOAS) / 3) * 100, 1) AS PERCENT_ACERTO
  FROM (SELECT CO_HABILIDADE, 
               SG_UF_PROVA,
               CASE WHEN RESP_ITEM = TX_GABARITO THEN 1 ELSE 0 END AS ACERTO, 
               COUNT(1) OVER (PARTITION BY SG_UF_PROVA) AS TOTAL_PESSOAS 
          FROM (SELECT A.*, 
                       C.CO_HABILIDADE, 
                       C.TX_GABARITO
                  FROM (SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 1 , 1) AS RESP_ITEM, 1 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 2 , 1) AS RESP_ITEM, 2 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 3 , 1) AS RESP_ITEM, 3 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 4 , 1) AS RESP_ITEM, 4 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 5 , 1) AS RESP_ITEM, 5 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 6 , 1) AS RESP_ITEM, 6 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 7 , 1) AS RESP_ITEM, 7 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 8 , 1) AS RESP_ITEM, 8 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 9 , 1) AS RESP_ITEM, 9 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 10, 1) AS RESP_ITEM, 10 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 11, 1) AS RESP_ITEM, 11 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 12, 1) AS RESP_ITEM, 12 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 13, 1) AS RESP_ITEM, 13 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 14, 1) AS RESP_ITEM, 14 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 15, 1) AS RESP_ITEM, 15 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 16, 1) AS RESP_ITEM, 16 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 17, 1) AS RESP_ITEM, 17 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 18, 1) AS RESP_ITEM, 18 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 19, 1) AS RESP_ITEM, 19 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 20, 1) AS RESP_ITEM, 20 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 21, 1) AS RESP_ITEM, 21 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 22, 1) AS RESP_ITEM, 22 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 23, 1) AS RESP_ITEM, 23 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 24, 1) AS RESP_ITEM, 24 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 25, 1) AS RESP_ITEM, 25 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 26, 1) AS RESP_ITEM, 26 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 27, 1) AS RESP_ITEM, 27 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 28, 1) AS RESP_ITEM, 28 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 29, 1) AS RESP_ITEM, 29 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 30, 1) AS RESP_ITEM, 30 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 31, 1) AS RESP_ITEM, 31 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 32, 1) AS RESP_ITEM, 32 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 33, 1) AS RESP_ITEM, 33 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 34, 1) AS RESP_ITEM, 34 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 35, 1) AS RESP_ITEM, 35 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 36, 1) AS RESP_ITEM, 36 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 37, 1) AS RESP_ITEM, 37 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 38, 1) AS RESP_ITEM, 38 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 39, 1) AS RESP_ITEM, 39 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 40, 1) AS RESP_ITEM, 40 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 41, 1) AS RESP_ITEM, 41 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 42, 1) AS RESP_ITEM, 42 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 43, 1) AS RESP_ITEM, 43 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 44, 1) AS RESP_ITEM, 44 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 UNION ALL
                        SELECT CO_PROVA_CN, SG_UF_PROVA, SUBSTR(TX_RESPOSTAS_CN, 45, 1) AS RESP_ITEM, 45 AS COD_ITEM FROM MICRODADOS_ENEM me WHERE TP_PRESENCA_CN = 1 
                     ) AS A
                 INNER JOIN (SELECT (CO_POSICAO - (MIN_CO_POSICAO - 1)) AS CO_POSICAO, 
                                    CO_PROVA,
                                    CO_HABILIDADE,
                                    TX_GABARITO
                               FROM (SELECT CO_POSICAO, 
                                            CO_PROVA,
                                            CO_HABILIDADE,
                                            TX_GABARITO,
                                            MIN(CO_POSICAO) OVER (PARTITION BY CO_PROVA) AS MIN_CO_POSICAO  
                                       FROM ITENS_PROVA ip 
                                      WHERE SG_AREA = 'CN' 
                                      order BY CO_PROVA, CO_POSICAO
                                     ) AS B
                             ) AS C ON A.CO_PROVA_CN = C.CO_PROVA AND A.COD_ITEM = C.CO_POSICAO
                  INNER JOIN (SELECT COUNT(NU_INSCRICAO) AS qtd,
                                     SG_UF_PROVA,
                                     CO_UF_PROVA
                                FROM MICRODADOS_ENEM me 
                               WHERE TP_PRESENCA_CN = 1
                               GROUP BY SG_UF_PROVA, CO_UF_PROVA
                               ORDER BY qtd DESC
                               LIMIT 5
                             ) AS ESTADO ON ESTADO.SG_UF_PROVA = A.SG_UF_PROVA
                 ) AS D
         ) AS E 
GROUP BY CO_HABILIDADE, SG_UF_PROVA ;